import assert from 'node:assert/strict';import{createRequire}from'node:module';import{mkdtemp,rm,access,mkdir,readFile}from'node:fs/promises';import{join,resolve}from'node:path';import{tmpdir}from'node:os';import{spawn,execFileSync}from'node:child_process';
const require=createRequire(import.meta.url),root=resolve(import.meta.dirname,'..'),dir=await mkdtemp(join(tmpdir(),'temple-demo-http-')),php=process.env.PHP_BIN||'php',base='http://127.0.0.1:8094',env={...process.env,TEMPLE_CONFIG:join(dir,'config.php')};let server,browser,count=0;
const check=(v,n)=>{assert.ok(v,n);count++;console.log('PASS: '+n);};
try{
 execFileSync(php,['-r',`$c=['base_url'=>${JSON.stringify(base)},'data_dir'=>${JSON.stringify(join(dir,'private'))},'secure_cookies'=>false];file_put_contents(getenv('TEMPLE_CONFIG'),'<?php return '.var_export($c,true).';');`],{env});
 server=spawn(php,['-S','127.0.0.1:8094','-t',join(root,'public')],{env,stdio:'ignore'});
 for(let i=0;i<50;i++){try{await fetch(base);break;}catch{await new Promise(r=>setTimeout(r,100));}}
 let r=await fetch(base+'/demo-api.php');const catalog=await r.json();const cookie=r.headers.get('set-cookie').split(';')[0];check(r.ok&&catalog.types.adult.price===1000,'demo works without Stripe keys, app key or live database setup');check(r.headers.get('cache-control').includes('no-store'),'demo API is never cached');
 const post=(body)=>fetch(base+'/demo-api.php',{method:'POST',headers:{cookie,'Content-Type':'application/json'},body:JSON.stringify({csrf:catalog.csrf,...body})});
 r=await post({action:'reserve',date:catalog.today,type:'adult',quantity:1,name:'Guest',csrf:'wrong'});check(r.status===403,'demo creation protected against CSRF');
 r=await post({action:'reserve',date:catalog.today,type:'adult',quantity:1,name:'Guest',total:1});let data=await r.json();check(r.status===201&&data.booking.total===1000,'client price tampering ignored');
 r=await post({action:'outcome',token:data.booking.token,outcome:'failed'});check((await r.json()).booking.status==='failed','payment failure can be practised through HTTP');
 r=await post({action:'checkin',token:'a'.repeat(64)});check(r.status===422,'unknown QR cannot be checked in');
 if(process.env.TEMPLE_BROWSER==='1'){
  const {chromium}=require('playwright');browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--single-process','--disable-gpu','--disable-software-rasterizer']});
  const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+'/');check(await page.getByRole('heading',{name:'Less scrolling. More still water.'}).isVisible(),'fishery-led homepage visible');check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'new homepage fits 390px mobile');await page.getByRole('button',{name:'Menu ☰'}).click();check(await page.locator('#site-nav').isVisible(),'mobile navigation opens');
  const shots=process.env.TEMPLE_SCREENSHOTS;if(shots){await mkdir(shots,{recursive:true});await page.screenshot({path:join(shots,'fishery-mobile.png'),fullPage:true});await page.setViewportSize({width:1440,height:1050});await page.goto(base+'/');await page.screenshot({path:join(shots,'fishery-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});}
  await page.goto(base+'/demo.php?quantity=2');await page.getByRole('button',{name:'Choose tickets'}).click();await page.getByLabel('Name on demo ticket').fill('Practice Angler');await page.getByRole('button',{name:'Review test checkout'}).click();await page.getByRole('heading',{name:'All set for a trial run.'}).waitFor();check(await page.getByRole('heading',{name:'All set for a trial run.'}).isVisible(),'demo reaches simulated checkout without card details');
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile checkout fits screen');if(shots)await page.screenshot({path:join(shots,'demo-checkout-mobile.png'),fullPage:true});
  await page.getByRole('button',{name:'Simulate successful payment'}).click();await page.getByRole('heading',{name:'Your tickets are ready.'}).waitFor();check(await page.locator('.digital-ticket').count()===2,'browser journey creates two individual demo QR tickets');
  const privateUrl=page.url(),qr=await page.locator('.ticket-code img').first().getAttribute('src'),token=new URL(qr,base).searchParams.get('token');await page.addScriptTag({url:base+'/vendor/jsQR.js'});
  const decoded=await page.evaluate(async()=>{const img=document.querySelector('.ticket-code img');await img.decode();const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const ctx=c.getContext('2d');ctx.drawImage(img,0,0);const d=ctx.getImageData(0,0,c.width,c.height);return window.jsQR(d.data,d.width,d.height)?.data;});check(decoded===base+'/demo-scan.php?token='+token,'actual rendered QR decodes to demo-only URL');
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile demo tickets fit screen');if(shots)await page.screenshot({path:join(shots,'demo-ticket-mobile.png'),fullPage:true});
  await page.goto(decoded);await page.getByRole('button',{name:'Confirm demo check-in'}).waitFor();check(!(await page.locator('#scan-result').textContent()).includes('Practice Angler'),'public demo scan does not reveal ticket-holder name');await page.getByRole('button',{name:'Confirm demo check-in'}).click();await page.getByRole('heading',{name:'Already checked in'}).waitFor();check(true,'explicit demo check-in shows already-used state');await page.reload();await page.getByRole('heading',{name:'Already checked in'}).waitFor();check(await page.getByRole('button',{name:'Confirm demo check-in'}).count()===0,'reload cannot repeat demo check-in');
  await page.goto(privateUrl);await page.getByText('Try a refunded-ticket scenario').click();await page.getByRole('button',{name:'Simulate full refund'}).click();await page.getByRole('heading',{name:'Demo refund recorded.'}).waitFor();await page.goto(decoded);await page.getByRole('heading',{name:'Demo ticket refunded'}).waitFor();check(true,'demo refund invalidates existing QR across pages');check(errors.length===0,'demo journey has no browser JavaScript errors');
 }
 let exists=true;try{await access(join(dir,'private/temple.sqlite'));}catch{exists=false;}check(!exists,'entire demo never creates or writes the live booking database');
 console.log(`\n${count} demo HTTP/browser checks passed.`);
}finally{if(browser)await browser.close();if(server){server.kill();await new Promise(r=>server.once('exit',r));}await rm(dir,{recursive:true,force:true});}
