import assert from 'node:assert/strict';import{mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{resolve,join}from'node:path';import{execFileSync}from'node:child_process';
const root=resolve(import.meta.dirname,'..'),dir=await mkdtemp(join(tmpdir(),'temple-upgrade-')),php=process.env.PHP_BIN||'php',env={...process.env,TEMPLE_CONFIG:join(dir,'config.php')};
const run=code=>execFileSync(php,['-r',code],{env,encoding:'utf8'});
try{
 run(`require ${JSON.stringify(join(root,'vendor/autoload.php'))};mkdir(${JSON.stringify(join(dir,'data'))},0700);$c=['data_dir'=>${JSON.stringify(join(dir,'data'))},'app_key'=>str_repeat('x',64),'stripe_mode'=>'test'];file_put_contents(getenv('TEMPLE_CONFIG'),'<?php return '.var_export($c,true).';');$s=new Temple\\Store($c['data_dir'].'/temple.sqlite');$s->db->exec(file_get_contents(${JSON.stringify(join(root,'tests/fixtures/restricted-schema.sql'))}));$s->db->exec("CREATE TABLE migrations(version TEXT PRIMARY KEY,applied_at INTEGER NOT NULL);INSERT INTO migrations VALUES('001.sql',1);");$s->run("INSERT INTO users(email,name,password,role) VALUES('staff@example.test','Staff','unused','admin')");$s->run("INSERT INTO bookings(reference,token,date,type_name,quantity,unit_price,total,name,email,status,expires_at,created_at,paid_at) VALUES('TS-OLD','old-token','2099-01-01','Adult',1,1000,1000,'Existing','old@example.test','paid',1,1,1)");$s->run("INSERT INTO tickets(booking_id,token,checked_at,checked_by) VALUES(1,'old-qr',123,1)");$s->run("INSERT INTO audit(user_id,action,booking_id,created_at) VALUES(1,'check_in',1,123)");$s->run("INSERT INTO outbox(booking_id,status) VALUES(1,'sent')");`);
 const output=execFileSync(php,[join(root,'bin/console.php'),'migrate'],{env,encoding:'utf8'});assert.match(output,/Applied 002_booking_states.sql/);console.log('PASS: existing restricted schema upgraded');
 const data=JSON.parse(run(`require ${JSON.stringify(join(root,'app/bootstrap.php'))};echo json_encode(['booking'=>$s->one('SELECT * FROM bookings WHERE id=1'),'ticket'=>$s->one('SELECT * FROM tickets WHERE id=1'),'audit'=>$s->one('SELECT * FROM audit WHERE id=1'),'outbox'=>$s->one('SELECT * FROM outbox WHERE booking_id=1'),'foreign'=>$s->all('PRAGMA foreign_key_check'),'enabled'=>$s->setting('bookings_enabled')]);`));
 assert.equal(data.booking.reference,'TS-OLD');assert.equal(data.ticket.checked_by,1);assert.equal(data.ticket.checked_at,123);assert.equal(data.audit.booking_id,1);assert.equal(data.outbox.status,'sent');assert.deepEqual(data.foreign,[]);assert.equal(data.enabled,'0');console.log('PASS: booking IDs, customer details, check-ins, audit and email links preserved; bookings stay OFF');
 const value=run(`require ${JSON.stringify(join(root,'app/bootstrap.php'))};$s->run("UPDATE settings SET value='1' WHERE key='bookings_enabled'");$b=$booking->reserve(date('Y-m-d'),1,1,'New','new@example.test');echo $b['status'];`);assert.equal(value,'creating');console.log('PASS: real reservation creation works after schema upgrade');
 console.log('\n3 upgrade checks passed.');
}finally{await rm(dir,{recursive:true,force:true});}
